name: Test Runner

on:
  workflow_dispatch:

jobs:
  test:
    runs-on: [self-hosted, proxmox]
    steps:
      - name: Whoami
        run: |
          echo "User: $(whoami)"
          echo "Host: $(hostname)"
          pwd
